// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHQMM7HYMmEgxBr_9Ez_HudneXV9kPhs',
    appId: '1:1016621839875:web:22cf0e9c33da4a854f0036',
    messagingSenderId: '1016621839875',
    projectId: 'library-management-de193',
    authDomain: 'library-management-de193.firebaseapp.com',
    storageBucket: 'library-management-de193.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_bjPUn8GReoCT6AQfQb8dQ_qZxNw8wMc',
    appId: '1:1016621839875:android:46cb02191a6609534f0036',
    messagingSenderId: '1016621839875',
    projectId: 'library-management-de193',
    storageBucket: 'library-management-de193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlim0YBve7JZi-67O4ctrzR2dnLb_KRNc',
    appId: '1:1016621839875:ios:00af36a79d2ae3e34f0036',
    messagingSenderId: '1016621839875',
    projectId: 'library-management-de193',
    storageBucket: 'library-management-de193.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlim0YBve7JZi-67O4ctrzR2dnLb_KRNc',
    appId: '1:1016621839875:ios:00af36a79d2ae3e34f0036',
    messagingSenderId: '1016621839875',
    projectId: 'library-management-de193',
    storageBucket: 'library-management-de193.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaHQMM7HYMmEgxBr_9Ez_HudneXV9kPhs',
    appId: '1:1016621839875:web:56eb950bc3860d884f0036',
    messagingSenderId: '1016621839875',
    projectId: 'library-management-de193',
    authDomain: 'library-management-de193.firebaseapp.com',
    storageBucket: 'library-management-de193.firebasestorage.app',
  );
}
